# Converts emotes.json into a compact JS source file the builder page can load from file://
# (fetch() of a local .json is blocked under file://, a <script src> is not).

param(
    [string]$In  = "$PSScriptRoot\..\data\emotes.json",
    [string]$Out = "$PSScriptRoot\..\data\rpemotes.js",
    [string]$SourceId    = 'rpemotes-reborn',
    [string]$SourceLabel = 'rpemotes-reborn (built-in)'
)

$ErrorActionPreference = 'Stop'

# section -> [groupId, groupLabel, chatCommand]
# Keys are bare table names ("Emotes"), matching the parser, which strips the
# RP./DP. prefix so both resource families parse the same way.
$map = @{}
$map['Emotes']       = @('emotes', 'Emotes',  '/e')
$map['Dances']       = @('dances', 'Dances',  '/e')
$map['PropEmotes']   = @('props',  'Props',   '/e')
# /nearby, not /e -- see the note in parse-emotes.ps1
$map['Shared']       = @('shared', 'Shared',  '/nearby')
$map['AnimalEmotes'] = @('animal', 'Animal',  '/e')
$map['Walks']        = @('walks',  'Walks',   '/walk')
$map['Expressions']  = @('moods',  'Moods',   '/mood')

$all = Get-Content $In -Raw -Encoding UTF8 | ConvertFrom-Json
if (@($all).Count -eq 0) { throw "no rows in $In" }

$groups = @()
foreach ($k in @('Emotes','Dances','PropEmotes','Shared','AnimalEmotes','Walks','Expressions')) {
    $g = $map[$k]
    $groups += [ordered]@{ id = $g[0]; label = $g[1]; command = $g[2] }
}

# rows: [name, display, groupId, dict, anim, prop, flag, partner, seen, total, drifted, marks]
#   marks packs the four things the list's author states outright into one small
#   integer, because all of them are rare and a column of zeroes for 1,881 rows
#   is pure weight:
#     1 = adult, 2 = abusable, 8 = has a particle effect,
#     4 = only works while IN a vehicle, 16 = only works while OUT of one
#   (4 and 16 come from the same Lua key with opposite values -- see the parser)
#   drifted = the command exists in the original too, but points at a DIFFERENT
#   animation there. It works on any server; it just does not look the same.
#   seen/total = in how many of the compared emote resources this name appears.
#   seen == total means every one of them has it, including the independent
#   original dpemotes -- the closest thing to "works on any server".
#   display omitted when identical to name.
#   dict/anim/prop are the raw strings from the Lua -- they are what tells you
#   objectively what the emote is (e.g. "anim@amb@nightclub@dancers@podium_dancers@").
$rows = @()
foreach ($e in $all) {
    if (-not $map.ContainsKey($e.Section)) { continue }   # RP.Exits has no chat command
    # The 30 the list's author marks AdultAnimation do not go into the page at
    # all. They were held behind a checkbox for a while, which still meant
    # shipping them and offering a way to show them; leaving them out of the
    # generated data is the honest version of the same decision. emotes.json
    # still has them, so this is one line to undo.
    if ($e.Adult) { continue }
    $gid = $map[$e.Section][0]
    # -ceq, not -eq: PowerShell's default comparison is case-INsensitive, so
    # "Dance" -eq "dance" is true and the capitalised label would be thrown away.
    $disp = if ($e.Display -ceq $e.Name) { '' } else { $e.Display }
    $seen  = if ($null -ne $e.Seen)  { [int]$e.Seen }  else { 0 }
    $total = if ($null -ne $e.Total) { [int]$e.Total } else { 0 }
    $drift = if ($null -ne $e.Drifted) { [int]$e.Drifted } else { 0 }
    $marks = 0
    if ($e.Abusable) { $marks = $marks -bor 2 }
    if ($e.Vehicle -eq 1) { $marks = $marks -bor 4 }    # only works in a vehicle
    if ($e.Vehicle -eq 2) { $marks = $marks -bor 16 }   # only works out of one
    if ($e.Ptfx)     { $marks = $marks -bor 8 }
    $rows += ,@($e.Name, $disp, $gid, $e.Dict, $e.Anim, $e.Prop, $e.Flag, $e.Partner, $seen, $total, $drift, $marks)
}

$payload = [ordered]@{
    id     = $SourceId
    label  = $SourceLabel
    groups = $groups
    rows   = $rows
}

$json = $payload | ConvertTo-Json -Depth 6 -Compress
$js = @"
// Generated by tools/make-data.ps1 from rpemotes-reborn client/AnimationList.lua
// rows: [name, display (blank = same as name), groupId, dict, anim, prop, flag, partner, seen, total, drifted, marks]
// marks: 1 = adult, 2 = abusable, 4 = only in a vehicle, 8 = particle effect, 16 = only out of a vehicle
window.EMOTE_SOURCES = window.EMOTE_SOURCES || {};
window.EMOTE_SOURCES['$SourceId'] = $json;
"@

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText((Resolve-Path -LiteralPath (Split-Path $Out -Parent)).Path + '\' + (Split-Path $Out -Leaf), $js, $utf8NoBom)

"wrote  : $Out"
"emotes : $($rows.Count)"
"groups : $($groups.Count)"
"size   : $([math]::Round((Get-Item $Out).Length/1KB,1)) KB"

# Inline the same payload into index.html between the DATA markers, so the page is a
# single self-contained file. A relative <script src> is not guaranteed to resolve when
# the page is opened by double-clicking (file://), and this sidesteps the question.
# NOTE: PowerShell variable names are case-insensitive, so $Html and $html would be
# the same variable. Keep the path and the contents in clearly distinct names.
$htmlPath = Join-Path (Split-Path $PSScriptRoot -Parent) 'index.html'
if (Test-Path $htmlPath) {
    $doc = [System.IO.File]::ReadAllText($htmlPath, [System.Text.Encoding]::UTF8)
    $begin = '<!--DATA-BEGIN-->'
    $end   = '<!--DATA-END-->'
    $i = $doc.IndexOf($begin)
    $j = $doc.IndexOf($end)
    if ($i -ge 0 -and $j -gt $i) {
        $inline = $begin + "`r`n<script>`r`n" + $js + "`r`n</script>`r`n" + $end
        $doc = $doc.Substring(0, $i) + $inline + $doc.Substring($j + $end.Length)
        [System.IO.File]::WriteAllText($htmlPath, $doc, $utf8NoBom)
        "inlined: $htmlPath  ($([math]::Round((Get-Item $htmlPath).Length/1KB,1)) KB)"
    } else {
        Write-Warning "DATA markers not found in $htmlPath -- left untouched"
    }
}
